import Head from 'next/head'
import Link from 'next/link'
import React,{useEffect,useState,useRef} from 'react'
import Script from 'next/script'
import {Heading, Grid,Text, Image, Tooltip, Flex, Input, FormControl, FormLabel, Box,Highlight, Button, GridItem} from '@chakra-ui/react'
import Sidebar from '../components/Sidebar'
import Dashboard from './dashboard'
import Pricing from './pricing'

export default function Home() {
  return (
    <>
      <Head>
        <title>Rhema AI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex direction="row" justify="center" align="center">
        <Button variant="outline"><Link href="/signup">Sign up</Link></Button>
        <Button variant="solid"><Link href="/login">Login</Link></Button>
      </Flex>
    </>
  )
}
